apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1  # You can scale this number based on requirements
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dockyvenkat/dcsc-frontend:latest  # Replace with your built Docker image
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80   # Exposed service port
      targetPort: 3000  # Container's port
  type: LoadBalancer  # For external access, use LoadBalancer or NodePort
