apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dockyvenkat/dcsc-backend:latest  # Replace with your built Docker image
          ports:
            - containerPort: 3001
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/vision-api-key.json"
            - name: REDIS_HOST
              value: "redis"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001   # Expose the backend on port 3001
      targetPort: 3001
  type: ClusterIP  # Internal access, use LoadBalancer for external
