# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the Node.js application's port
EXPOSE 3001

# Environment variable to connect to Redis
ENV REDIS_HOST=redis  

# Command to run the Node.js app
CMD ["node", "index.js"]
