apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: dockyvenkat/dcsc-python:latest  # Replace with your built Docker image
          ports:
            - containerPort: 5000  # If your Python app uses a specific port
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 5000   # Expose the python service
      targetPort: 5000
  type: ClusterIP  # Internal access
